
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzosgtmmjswjtjvibpye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6b3NndG1tanN3anRqdmlicHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MDkxNjQsImV4cCI6MjA1OTQ4NTE2NH0.Ky2APyH6-3v52zWQonNV9fJr9PG5L5oS9zaZe12IWp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
